### ISSUE TITLE
Resources folder for neuron installation not set in settings, cannot install.

### ISSUE THREAD

**Issue by Riseryn** [royto/kalliope_neuron_movie_db#11]
Bonjour
j'ai voulu installer votre neuron en faisant kalliope install --git-url https://github.com/royto/kalliope_neuron_movie_db.git
j'ai le message d'erreur 
Resources folder for neuron installation not set in settings, cannot install.

kalliope version 0.6.0
que faut il modifier ?
Merci

**Comment by royto** [comment]
Salut @Riseryn,

as tu configuré ton `resource_directory` dans le fichier settings.yml => la doc [ici](https://kalliope-project.github.io/kalliope/settings/settings/#resources-directory)

Pas encore installé la version 0.6.0 de kalliope, donc je ne suis pas sur que ca marche sans une maj du neuron ...

**Comment by Riseryn** [comment]
Bonjour.
j'ai decommente dans settings pour avoir cela
resource_directory:
  neuron: "resources/neurons"
  stt: "resources/stt"
  tts: "resources/tts"
  signal: "resources/signal"
  trigger: "resources/trigger"

c'est bien cela qu'il faut faire ?
malgré cela j'ai toujours la même erreur quel que soit le neuron que je tente d'installer

**Comment by Riseryn** [comment]
Bonjour.
J'ai réinstalle kalliope avec la commande pip3, au lieu du script,  et je n'ai plus ce message d'erreur.
Le neuron s'installe correctement.
Néanmoins il ne fonctionne pas car lorsque je demande,par exemple, " recherche le film Avatar" la commande n'est pas comprise.
Peut être une mise à jour à faire pour la version 0.6.0 de kalliope ?

**Comment by royto** [comment]
Salut, 

As tu des logs ?

As tu bien configuré un neuron ? Est il bien pris en compte ?

**Comment by Riseryn** [comment]
Salut
pas de log d'errerur;
Comment configurerun neuron?
Merci

**Comment by Riseryn** [comment]
Bonjour
j'ai compris une partie de ce que je ne comprenais pas dans le fonctionnement de kalliope ;).
Ce neuron fonctionne donc bien avec la version 0.6.0;
Merci pour les réponses.
Ce topic peut être marqué comme résolu
Cordialement
