### ISSUE TITLE
error with debug list

### ISSUE THREAD

**Issue by Alaindr** [royto/kalliope_neuron_movie_db#6]
SSLError: HTTPSConnectionPool(host='api.themoviedb.org', port=443): Max retries exceeded with url: /3/search/movie?query=le+bal+des+vampires&api_key=here is my key&language=fr (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))

**Comment by royto** [comment]
What is your version of tmdbsimple 

use `pip show tmdbsimple `

works fine on my machine with version 2.2.0

**Comment by royto** [comment]
I just release a new version with TV show support including tmdb update to last version 2.2.0). 

Could you update and try ?

**Comment by Alaindr** [comment]
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Name: tmdbsimple
Version: 1.6.1
Summary: A Python wrapper for The Movie Database API v3
Home-page: https://github.com/celiao/tmdbsimple
Author: Celia Oakley
Author-email: celia.oakley@alumni.stanford.edu
License: UNKNOWN
Location: /usr/local/lib/python2.7/dist-packages
Requires: requests
Required-by:

**Comment by Alaindr** [comment]
i've update.... but the same version.
I do a new installation... of kalliope....

**Comment by Alaindr** [comment]
ok with new installation of kalliope... cool

**Comment by Alaindr** [comment]
thank

**Comment by royto** [comment]
Cool. I close the issue
